### ISSUE TITLE
Feedback of RME toggle button state?

### ISSUE THREAD

**Issue by mat4st** [shells-dw/streamdeck-totalmix#1]
Hi

It's great to control Totalmix from StreamDeck via OSC! I switch the 48V phantom power on and of. But even better would it be, if there could be a toggle switch, which reflects the state of the switch in TotalMix. Would that be possible to display the state of the 48V switch (or others) on StreamDeck?

**Comment by shells-dw** [comment]
Hi mat4st
I can look into migrating those plain toggle actions out of the "Control Channel" action into the toggle one, that should be possible. I mainly did it that way so it's logically in the "Control Channel" actions as that's basically what you do.
Theoretically it should be possible to read the current state of those, doing the same for mute and solo - but I'm currently a bit rusty on the topic, haven't looked into it since I released it, as it worked rather flawlessly and I've just used it.
I'll look into it within the next days and get back to you.

Thanks for the input, haven't thought about doing it despite it's kind of obvious now that I think about it ;-)

**Comment by mat4st** [comment]
Hi

Sounds great, thanks a lot, looking forward to hear from you again!

Cheers!

**Comment by JasonGosling** [comment]
Feels a tiny bit churlish to ask for anything else as this plug in set works really well but 48v phantom as a toggle would be really handy. Did you ever get chance to have a look?

**Comment by JasonGosling** [comment]
Kind of yes but I was hoping for an icon change to reflect it's state. I can't seem to see if that's possible, even with the new changes. Cheers.

**Comment by shells-dw** [comment]
Alright, got you. In the version I released today (find it in the [Release](https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release) folder of this repo) I added the option to use two icons per module, so StreamDeck toggles between those when you press the button. That however doesn't reflect what's set directly on the device (e.g. if phantom power is already on when you start StreamDeck/your PC or if you toggle phantom power from the device itself or with TotalMix) but might be a bit of an usability upgrade for the time being. If you're constantly enabling and disabling phantom power (not sure why you would need to do that, phantom power can pretty much be constantly on if you ask me - but hey, however you please), you could set your Snapshot to have it off on all channels by default - or just make sure it's off before you start a session with StreamDeck.
I'm careful with querying the device status constantly, doing it too much (even with async processing) makes the StreamDeck plugin feel slow or laggy when waiting for it, or with detached querying updates are reflected only seconds (to quite a few seconds) after the change due to how OSC works and it's implemented by RME.

To dive in that a bit deeper, you can't just programmatically ask the device "how's phantom power set on hardware input 1?" and get a proper response (like "1" or something rather useable), instead you have to query a dump of all current states at once, then the device responds back in a multi package response with every single value there is in the device, that then needs to get received, combined, parsed and correctly interpreted. For once it takes time for the device to respond, it needs to be transferred, processed, etc. and all of that adds up.
I've already detached that in a async background process that holds the values to request in the Toggle Channel module, but adding it to another module additionally it's just not as quick and useful like I'd like it to be when multiple buttons of both modules are set up on the StreamDeck.
Now, I could try and detach that as a plugin wide background process and see how that works, however I don't really use RME boxes anymore, so I do just a little maintenance work on the plugin and I'm not too fancy on spending a day rewriting a plugin I don't even use myself anymore just for the sake of it, to be completely honest.

**Comment by JasonGosling** [comment]
Really appreciate you checking in about this. What you added today does more than enough for me now I can see it. I'm just moving towards having the UCX out of view and nice to know the mic is off before swapping it out or whatever. Plenty of places to get this feedback but this visual toggle on the stream deck is so immediate. Thanks a lot for your time, especially as you've gone UA, it saves me so many odd seconds and it all adds up. Also thanks for the dive into how fiddly it is.

**Comment by mat4st** [comment]
Hey

Thanks a lot, that's all fine!
I can perfectly understand you. Looks like that's the best way to do it.

Thanks for your time and help!

Best,
Mat


Von: shells-dw ***@***.***>
Gesendet: Mittwoch, 20. April 2022 17:28
An: shells-dw/streamdeck-totalmix ***@***.***>
Cc: mat4st ***@***.***>; Author ***@***.***>
Betreff: Re: [shells-dw/streamdeck-totalmix] Feedback of RME toggle button state? (#1)


Alright, got you. In the version I released today (find it in the Release<https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release> folder of this repo) I added the option to use two icons per module, so StreamDeck toggles between those when you press the button. That however doesn't reflect what's set directly on the device (e.g. if phantom power is already on when you start StreamDeck/your PC or if you toggle phantom power from the device itself or with TotalMix) but might be a bit of an usability upgrade for the time being. If you're constantly enabling and disabling phantom power (not sure why you would need to do that, phantom power can pretty much be constantly on if you ask me - but hey, however you please), you could set your Snapshot to have it off on all channels by default - or just make sure it's off before you start a session with StreamDeck.
I'm careful with querying the device status constantly, doing it too much (even with async processing) makes the StreamDeck plugin feel slow or laggy when waiting for it, or with detached querying updates are reflected only seconds (to quite a few seconds) after the change due to how OSC works and it's implemented by RME.

To dive in that a bit deeper, you can't just programmatically ask the device "how's phantom power set on hardware input 1?" and get a proper response (like "1" or something rather useable), instead you have to query a dump of all current states at once, then the device responds back in a multi package response with every single value there is in the device, that then needs to get received, combined, parsed and correctly interpreted. For once it takes time for the device to respond, it needs to be transferred, processed, etc. and all of that adds up.
I've already detached that in a async background process that holds the values to request in the Toggle Channel module, but adding it to another module additionally it's just not as quick and useful like I'd like it to be when multiple buttons of both modules are set up on the StreamDeck.
Now, I could try and detach that as a plugin wide background process and see how that works, however I don't really use RME boxes anymore, so I do just a little maintenance work on the plugin and I'm not too fancy on spending a day rewriting a plugin I don't even use myself anymore just for the sake of it, to be completely honest.

-
