### ISSUE TITLE
Display Channel Name not match

### ISSUE THREAD

**Issue by anizen** [shells-dw/streamdeck-totalmix#16]
I am using digiface USB Supports 16(32) channels.

Starting from channel 10, the wrong name is called.

Channel 10 is (noname)
Channel 11 is the name of Channel 1
Channel 12 is the name of Channel 2
... 
Channel 16 is the name of Channel 6

But the function works fine.

And isn't the PH channel support? (image : software playback - the rightmost )

![1671545476223](https://user-images.githubusercontent.com/7676127/208689176-58de9147-3c08-4363-9463-994e6d825c68.jpg)

ver. [v3.1.4] (https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.1.4)

**Comment by shells-dw** [comment]
Hi, thanks for the bug report!
Whoopsi, good catch! In my recent rewrite I've accidentally totally neglected the possibility for double digit channels in the part where it reads the track name (the action still worked, as you mentioned, but didn't show the correct track name), so 0 became nothing as there is no channel 0, 11 became 1, etc.
I've already fixed it - it will be working in the next release!

That might still be a couple of days out though - I'm currently trying to track down a bug that makes the plugin crash or become unresponsive (for some constantly, for others barely if at all - including me, so it's a bit of a problem, sometimes I need to let it run for 3-5 hours before this bug happens, so it's not so easy to track down). Right now the plugin is a bit pulled inside out with logging all over the place, so I wouldn't want to fix a version that would probably just cause more issues for you for the moment.
Anyway, once that's sorted, the naming for channels >9 will work. Shouldn't be long 🤞.

Regarding the PH channels I sadly can't really develop for that, my old Fireface UC doesn't have the PH channels. It has 'virtual' channels to route into so the headphone jack can then be controlled by the Main channel - if I want to control any Line output I need to switch the Main channel to control the output channels instead then. It's a bit messy and not so comfortable as with other/bigger/newer devices, but heyho. So as I can't really test that or... well, know it it would work, sadly can't support.

Just as a shot in the dark however I would assume that these channels are accessible after the normal Output channels (so maybe from 17 for your interface?)
You could try setting both OSC ports to 24 channels instead of 16 and see if the channels 17/18 or so do anything to the PH channel. Having more channels in OSC than your device has doesn't do anything except for slow down the mirroring as there is a bit more data to be processed. You could try that and see what happens.
I'll update this issue once I've pushed the new version.

Thanks again

**Comment by anizen** [comment]
I'm always grateful to you and understand about the name error. Thank you!

I checked about PH.
I set the OSC port to 24 channels, but it can't see the channel after 16 channels.
Or did I set it up wrong?
Or have I misunderstood?

After I set it up, I completely shut down the stream deck and ran again.

![1671620671881](https://user-images.githubusercontent.com/7676127/208891629-8a917b47-5d64-4948-a512-615f9d66728d.jpg)
![1671620849796](https://user-images.githubusercontent.com/7676127/208891633-933f1313-555c-4867-b763-9beb87910062.jpg)
![1671620681335](https://user-images.githubusercontent.com/7676127/208891635-cc9b0648-04c6-4947-9dc9-59953b8566df.jpg)


Thanks :)

**Comment by shells-dw** [comment]
You're right, my bad.
I forgot I had not yet published the version that updates the dropdown during every time the plugin is loaded. Before it was set when the button is placed on the StreamDeck but never again thereafter.
Anyhow.
I've just published the [v3.2.0 release](https://github.com/shells-dw/streamdeck-totalmix/releases/tag/v3.2.0) that fixes not only that, but also channel names on channels above 9 (as promised in my last reply).

Also other stuff. So please check it out and let me know if that fixes the issues :)
Cheers

**Comment by anizen** [comment]
![messageImage_1671962075418](https://user-images.githubusercontent.com/7676127/209463601-33075b7b-7566-4152-9708-4597465cd27d.jpg)

Oh! all works fine!
As you said, I set it to 17 channels, but the PH is output and it works well.
Channel names are also output properly.
Thank you for correcting all errors.
Cheers!
