### ISSUE TITLE
Unable to send OSC commands to different computer on local network

### ISSUE THREAD

**Issue by larskendall** [shells-dw/streamdeck-totalmix#19]
We've been using your plugin for a while and have really liked it, but just the other night it seemed to stop working in our streaming setup, where we have a Stream Deck on one computer sending OSC commands to another computer on the network.

Nothing else has changed in our setup, and we've confirmed that everything else is functioning as expected, so we're suspecting now that there may have been an update to the plugin which removed some functionality that we were relying on.

It seems like we were able to specify an IP address from within each Stream Deck command before, and that that functionality has disappeared recently. Is this the case? And is there any way for us to continue using the plugin as we were before?

Thanks so much for your work on the plugin!

**Comment by larskendall** [comment]
It looks like this was something that changed with the 3.0.0 version. I was able to drop back to an older version and install it as a separate plugin to get it working the way it was before.

Feel free to close this issue if this use case is something you've officially stopped supporting. I'll leave it open for now just in case other people are running into a similar issue.

**Comment by shells-dw** [comment]
Hi Lars,

yes, I updated the plugin last week and updated a whole lot of things.
Sorry for the inconvenience caused by that, but I changed and improved so many things over the cause of a couple of months before asking Elgato to update the plugin for everybody (making sure a stable and reliable version is pushed to all users), and partly due to how StreamDeck and their update process works, I couldn't make sure every possible setup can be migrated to 'just work'.

*Sending commands to a TotalMix instance in the network is still supported* though, I just changed the way how this is implemented due to a plentitude of reasons. It has moved to a central location/config file. Please refer to the [plugin's readme here on GitHub](https://github.com/shells-dw/streamdeck-totalmix#deshellstotalmixexeconfig) on how to enter the IP of the target machine - and take a look on the [section above on how to setup TotalMix](https://github.com/shells-dw/streamdeck-totalmix#setup-for-osc) too.

In case you set this up correctly according to the readme but it should still not work, report back please.

Also, please let me know if you would indeed need the functionality of having different buttons sending commands to _different_ TotalMix instances, I could quickly make a version that supports that for you. Otherwise you should be fine following the setup steps in the linked readme.

Cheers

**Comment by shells-dw** [comment]
Hi,
you're fine, don't worry, I can understand you very well - and English is not my native language either 😃 

You're right. Addressing 2 different computers is not possible with the current version anymore. I have not heard about any setup like that and thus removed it - but I was obviously wrong there.

Give me a bit and I'll provide you with a version that can be used with multiple PCs again. However - mirroring of settings from both machines will then (for the time being) not be possible.

**Comment by shells-dw** [comment]
[de.shells.totalmix_hotfix.zip](https://github.com/shells-dw/streamdeck-totalmix/files/10374745/de.shells.totalmix_hotfix.zip)
I've very hacky re-added the per-Button IP/Port settings and disabled mirroring and the side-effects of doing so.

Please have a look and see if it works for you as it has.

**Comment by M-Jibal** [comment]
Thank you for your quick feedback. I was impressed.
Unfortunately it doesn't work.
![image](https://user-images.githubusercontent.com/122289017/211439392-8bf10892-c55f-4f75-94c5-4e05efd57661.png)
![image](https://user-images.githubusercontent.com/122289017/211439423-85ba6f10-dd5a-4816-b6f0-d08e444055ae.png)
![image](https://user-images.githubusercontent.com/122289017/211439441-f1f5ac1a-0daa-4e59-a118-282a8c737390.png)
I'll wait for other solutions or updates.

**Comment by shells-dw** [comment]
[I've created an archive repository for the latest v2 version.](https://github.com/shells-dw/streamdeck-totalmix-classic/releases)
This is the version that was available in the Elgato StreamDeck Store before I asked them to push the v3 release that is online now.
Hence, it should work for you like it did before. Sorry for the inconvenience.

It will install as an additional plugin (with the name extension "Classic") so it will not be overwritten by future updates of the normal version.

**Comment by M-Jibal** [comment]
It finally worked. you saved me.
Thank you so much.

**Comment by shells-dw** [comment]
Given I kind of caused the issue in the first place, it's only fair... but anyway, you're welcome :)
