### ISSUE TITLE
Cannot recognize channel or change ports anymore 

### ISSUE THREAD

**Issue by robdiesalot** [shells-dw/streamdeck-totalmix#20]
Hello! I have been using the plugin for a long time now and its always been working well and reliable.
Today, I had this happen to me. It seems that default settings work (RME control is ok), but I can no longer adjust port/channels on specific buttons and the plugin has started behaving somewhat glitchy. Any idea whats going on here?
Running Windows 11 and tried a couple of different builds including the newest one.
![image](https://user-images.githubusercontent.com/122238938/211225061-1a153b8c-8b31-40c6-bcb9-2db64c8a4cfa.png)

**Comment by shells-dw** [comment]
Hi Rob,

since the update to v3.x two OSC listeners are needed, please have a look at the [readme](https://github.com/shells-dw/streamdeck-totalmix#updating-from-older-versions) here on GitHub, especially the ["Setup for OSC"](https://github.com/shells-dw/streamdeck-totalmix#setup-for-osc) section.
Once you've enabled the second OSC listener as described, I'm sure it'll work again (and even better than before 😉 

Sadly it's not easily possible to show a notification during update (or on the first launch) to make users aware - I could show a message on every StreamDeck launch but decided against that, that would be annoying.

**Comment by robdiesalot** [comment]
Hi, thanks for the reply!
I did follow the instructions and it does indeed work with TotalMix without any issues. The thing is, I was also using it to control Unreal Engine via OSC, just like in the following video:
https://youtu.be/bz7T_Tq2v-8

I think I would ideally need to send OSC commands on a different port (maybe even IP? not sure) to Unreal Engine so it doesnt collide with TotalMix. Currently, I still get the same issue once I launch UE. I understand its primarily not designed to do this, but maybe it could be slightly adjusted? :)

**Comment by shells-dw** [comment]
No worries.

Years ago I made a small [plugin that can send OSC messages](https://github.com/shells-dw/StreamDeck-OSC/tree/master/Release), which might actually be (way) easier than ... misusing the TotalMix plugin.
Also there is [this](https://apps.elgato.com/plugins/com.animapix.oscremote) available in the store. I didn't test that and it's not mine, I just found it in the store and maybe that's better than mine.

This is not a slight adjustment with this version anymore - especially since there are other plugins available that can send OSC commands.

**Comment by robdiesalot** [comment]
Yes! This little plugin you made might just be the thing! Will give it a go, makes the most sense.
Ive actually been looking for a plugin like this and honestly I dont think there is anything else out there. The OSC Remote is sadly not working anymore and wont install (not with current streamdeck version atleast)
Thanks a lot! Will try to get it running like this, RME control for my Fireface UC and the Send OSC for Unreal Engine.
I really appreciate your help :)

**Comment by shells-dw** [comment]
No worries.
Let me know if you encounter issues with the OSC plugin. I haven't really touched it in ages and don't really use it anymore myself 😉 
Did a quick test on my machine (latest Win 11 and StreamDeck version) though and it worked as it should.

It's a way less complex plugin, so implementing or changing anything there would be way easier than messing around with the TotalMix monster to achieve something that it's not really supposed to do in the first place 😅

I think I never pushed it to the store as there were other plugins already available doing the same (well, when I looked to push it in the store, not when I coded it 🤷‍♂️ )

I'll close the issue here now then.
