### ISSUE TITLE
OSC toggle channel function issue

### ISSUE THREAD

**Issue by yochubeats** [shells-dw/streamdeck-totalmix#29]
Hello. I am Japanese.
Thank you for making such a useful plugin.
The problem here is that I can't select Select Function for OSC: Toggle Channel Function.
![streamdeck](https://user-images.githubusercontent.com/124772569/217480278-c192fb13-3973-4e61-9a49-08d0b1d1c36c.jpg)
The channel I want to select is not displayed.
Please help if you have any solution.

**Comment by shells-dw** [comment]
Hi,
did you follow the setup instructions outlined in the [readme](https://github.com/shells-dw/streamdeck-totalmix#setup-for-osc)?

If so and you double-checked TotalMix is setup correctly and the issue still persists, please attach the plugin logfile to this issue. The log file is named `pluginlog.log` and you can find it in `%appdata%\Elgato\StreamDeck\Plugins\de.shells.totalmix.sdPlugin`

**Comment by yochubeats** [comment]
Thank you for your reply.
Following the setup does not help.
I am attaching the log file.
[pluginlog.log](https://github.com/shells-dw/streamdeck-totalmix/files/10684783/pluginlog.log)

**Comment by shells-dw** [comment]
Interesting.
Now that you ran the setup, can you try deleting and re-adding a button to the StreamDeck and see if that helps?
The reason for that is that the StreamDeck basically stores settings for that button when it is put there and if there was missing data at the point it was put there, it might not update now that it might work. Deleting and re-adding it would fix it in that case.
The log shows a lot of missing data for the buttons you tried and the only way I can think of off the top of my head how this could happen would be if the button was put there before it was set up correctly. I might need to think about if that can be handled programmatically, but for now, please try re-adding a button.

**Comment by yochubeats** [comment]
I tried it as described, but it didn't work.
Maybe it's because I updated the UCX II firmware to the latest version.
It was working fine until then.

**Comment by shells-dw** [comment]
I see. I wasn't aware of that update yet, seems it just came out last week.
I'll update my fireface too and look into it.

**Comment by yochubeats** [comment]
I'm sorry for troubling you. thank you.

**Comment by shells-dw** [comment]
So... I updated to the latest version of TotalMix and even tried the most recent TotalMix beta version I found (which is even newer than the one supplied with the newest drivers I believe). The plugin works well and as it should on my system. I looked at the corresponding OSC table RME provides for the TotalMix version and there's nothing breaking in there as far as I could see either, a couple additional values and commands, but that's not breaking anything with the plugin.

Now I don't own a UCX II hence can't test on that specific hardware, however the plugin controls TotalMix and not the actual hardware interface and TotalMix should act the same OSC-wise on every system with every hardware connected, so I doubt the reason is a firmware update for the interface. If it really should be, which is highly unlikely in my opinion, I'm out of options not having that interface myself and also it's something going wrong with the update anyway, as said TotalMix shouldn't act differently with different interfaces connected.

TotalMix is basically just an executable that reads and writes its data to a config file. When you update TotalMix, it just replaces the executable on disk and the config file should not be touched hence the new version should just load the previous settings.

As you have stated it worked before you updated, maybe there was an issue updating values from the config file. Or Windows might have blocked the new version in its firewall, so please check that as well.

If TotalMix isn't blocked in the firewall, please try the following before I spend time producing a version that has extended logging:

- Go to `Options` and remove the tick for `Enable OSC Control`
- Remove the ticks for 1 and 2 at `Submix linked to OSC controller`
- Go in `Options - Settings - OSC` and remove the ticks at "In Use" for both Remote Controllers 1 and 2.
- Hit OK to close the Settings window.
- Restart your PC
- After restart, enable both OSC Remote Controllers again, set them to 16 `number of faders per bank` if they're not already set there (just for a test, if it works afterwards, change them back to what you had before if it wasn't 16) and add the ticks you removed in the first 2 steps above again.
Then restart StreamDeck completely, not just the UI (or your PC, doesn't matter, StreamDeck would be sufficient) and try again.

I've seen TotalMix show ticks and values that were not actually set (rarely, but still), so removing and setting the options again would eliminate such an issue. It was never to this degree when I came across these issues, however I just want to be sure it's not just something easy like this.
It doesn't appear to be a general problem so something on your PC seems to cause this and before I spend an hour or two to make a custom version for you with more logging that just pokes in the dark -because frankly I have no idea what that could be if it's not firewall or TotalMix doing things it shouldn't-, I'd like to explore easier options first.

Please report back after you've tried this and we go from there.

**Comment by yochubeats** [comment]
Sorry for the inconvenience. I tried the steps above but it didn't work.
Trigger Global Function works fine. I can't seem to find the channel selection.
i'll try it too.

**Comment by shells-dw** [comment]
Ok. I'll look into what I can log that might be helpful here and implement that in a special version. I'll update you.

Until then you could disable mirroring in the config file by setting `mirroringRequested` to `false` (as outlined [here](https://github.com/shells-dw/streamdeck-totalmix#deshellstotalmixexeconfig) - which at least should get the plugin working again for now.

**Comment by yochubeats** [comment]
Channels are now displayed after restarting STREAM DECK or resetting TotalMix settings.
Sorry for the inconvenience. Thank you very much for your kind support.
I will continue to use this wonderful plugin. I'm really thankful to you.
