### ISSUE TITLE
OSC Mute/Solo Button Feedback

### ISSUE THREAD

**Issue by adamhorky** [shells-dw/streamdeck-totalmix#3]
Thank you for your work on this.  It helps a lot to use the streamdeck to control Totalmix.

We are using your implementation in our studio for streaming and have run into an issue.
In our setup an Engineer controls the audio using a control surface (Icon QConPro X) while the streamer is using a streamdeck.
With your plugin the streamer can now mute and unmute channels in the RME interface and it works well.
The problem we have run into is when the Engineer has muted or unmuted a channel and caused the streamdeck to be 'out of sync' where it reflects the incorrect mute state of the channel.

You appear to acknowledge this in the read.me - "if you then switch the status in TotalMix or by other means, it will not be reflected on the deck."

Is it possible that in a future update that the Streamdeck can reflect the state changes of the Mute button when someone is toggling it in Totalmix or using a Control Surface?

**Comment by shells-dw** [comment]
Hey there!
I've been off this project for over a year now, I've completely moved to UA interfaces and MacOS for that kind of work last year, so this project was kind of dead for me, to be honest - however I still got my Fireface UC laying around and used that for a project recently so I figured I'd give this a look again and maybe help some of you guys out that still use them. So - apologies for not responding anytime sooner.

Ok, got the point. I'll look into it, but no promises :)

**Comment by shells-dw** [comment]
I've published a new release that updates the buttons when TotalMix changes solo or mute. I've also sped up the intialization delay right after starting StreamDeck (well, more or less). Due to how I gather info from the device it still has some milliseconds to a second delay here and there, but it's not nearly as bad as my initial code back in the old version and should work just fine.
Again, I'm sorry for the long delay and not responding any sooner. I hope it's still worth the effort and will be useful for you.
Before I figured out how I get that in the new Elgato store now, you can download the new version from the [Release](https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release) folder - just install it in the StreamDeck software with the prompt after opening the file, that should overwrite the one from the store.
I'd appreciate if you'd let me know if that works for you.
Cheers!
