### ISSUE TITLE
need more channel

### ISSUE THREAD

**Issue by GitSKYHEE** [shells-dw/streamdeck-totalmix#4]
My RME device supports 16(32) channels.
But, this app supports 12(24) channels.
Do you have any plans to support more channels?

**Comment by shells-dw** [comment]
Hey there!
I've been off this project for over a year now, I've completely moved to UA interfaces and MacOS for that kind of work last year, so this project was kind of dead for me, to be honest - however I still got my Fireface UC laying around and used that for a project recently so I figured I'd give this a look again and maybe help some of you guys out that still use them. So - apologies for not responding anytime sooner.

I sure can add more channels, however I do not have any means of testing that at the moment (and I don't really see me getting my hands on another bigger RME device in foreseeable future) - so despite that should work, you'll have to try that out yourself.

I'm currently implementing other requests as well, I'll update you once I uploaded a new version. Hang in there, it shouldn't be too long anymore.
Cheers!

**Comment by shells-dw** [comment]
I've published a new release that _should_ support 16 channels now. As stated I can't test it for more than 12 due to the lack of an RME interface with that amount of channels, so I've just added the missing 4 channels and the logic behind those and keep my fingers crossed that actually works. 🤞 
Before I figured out how I get that in the new Elgato store now, you can download the new version from the [Release](https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release) folder - just install it in the StreamDeck software with the prompt after opening the file, that should overwrite the one from the store.
I'd appreciate if you'd let me know if that works for you.
Cheers!

**Comment by GitSKYHEE** [comment]
wow! Thanks shells-dw!
I tested it now and it works fine. (RME Digiface USB)

New Channels 13-16 all working.

Thanks again so much!
It is very useful.
Thank you. 😍😍😍
