### ISSUE TITLE
Talkback Toggle - Status Feedback

### ISSUE THREAD

**Issue by Nordfrequenz** [shells-dw/streamdeck-totalmix#7]
Thank You so much for this software!
It would be really nice, to see on the streamdeck whether the talkback is switched on or off. Especially when your are working in your DAW and you don't have the totalmix console window open this kind of status feedback would be very helpful.
Thanks you!
Marc

**Comment by shells-dw** [comment]
Hi Marc,

firstly, pardon my late response. My current job comes with long trips where I'm not at home - and that means not near my Fireface interface which I kind of need to make any changes on the plugin.

The thing with these live status updates from the interface is that it can take quite a while to update due to how OSC works and RME have implemented it and despite some async processing this causes the StreamDeck plugin to feel slow or laggy the more you do that (and it's probably not the greatest idea flooding the interface with constant status queries either I would assume). That's why I tend to avoid doing these.

However - I've added the option to set two icons for every module, meaning once you toggle the talkback (or any other toggle function like mute, dim, etc.) the icon will change its color by default - additionally you can select your own icon (or use the ones Elgato supplies). This doesn't reflect the changes on the interface itself - meaning if you toggle talkback or any other function on TotalMix or the device, the plugin will not know about that and be out of sync. If you just use the plugin, that should be fine though.

You can find the new version under the Releases folder in this repo.

Cheers
