### ISSUE TITLE
Build for Mac?

### ISSUE THREAD

**Issue by Bas-oneseconds** [shells-dw/streamdeck-totalmix#8]
Hi would it be possible to build this for Mac also?

**Comment by shells-dw** [comment]
Hi,
not easily due to how you can programmatically talk to Midi and OSC on MacOS. At the time I developed it, you couldn't run anything from StreamDeck as a program on MacOS as you can in Windows (which allows libraries to be loaded and used that are necessary to communicate over MIDI or OSC), only option was JavaScript, with which you can't talk Midi and not really easily to OSC either. I'm not sure how that has changed by now, I haven't been developing anything for StreamDeck in ages - but it wouldn't be something that's easily done. It would basically be a complete rewrite for a MacOS version.

I've switched to UA hardware years ago, and as this would be a complete rewrite of the software that would take me weeks on the side I won't be doing it just for the lulz, sorry.
